# Generated by Django 3.0.4 on 2021-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_no', models.CharField(default=None, max_length=12)),
                ('bank_password', models.CharField(default=None, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item_feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
