# Generated by Django 3.0.4 on 2021-03-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurant1', '0001_initial'),
        ('OrderingOnline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_feedback',
            name='Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant1.Item'),
        ),
        migrations.AddField(
            model_name='item_feedback',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderingOnline.customer'),
        ),
        migrations.AddField(
            model_name='alert',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant1.Order_confirm'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderingOnline.customer'),
        ),
        migrations.AddField(
            model_name='account_user',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer'),
        ),
    ]
