# Generated by Django 3.0.4 on 2021-03-25 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_boy', '0001_initial'),
        ('OrderingOnline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('final_amount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=6, default=40.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(default='Special', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(default='delicious', max_length=150)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('pimage', models.ImageField(upload_to='menu_images/')),
                ('category', models.CharField(default='delicious', max_length=150)),
                ('total', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('feedback', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(default=None, max_length=50)),
                ('Restaurant_photo', models.ImageField(upload_to='restaurant_images/')),
                ('status', models.BooleanField(default=False)),
                ('password', models.CharField(default=None, max_length=30)),
                ('uname', models.CharField(default=None, max_length=30)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('feedback', models.DecimalField(decimal_places=1, default=0.0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 3, 25, 14, 56, 5, 187820, tzinfo=utc))),
                ('status', models.CharField(default='not_delivered', max_length=150)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('cartdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.cart')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_confirm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('status', models.CharField(default='Ordered', max_length=15)),
                ('feedback', models.IntegerField(default=0)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 3, 25, 14, 56, 5, 187820, tzinfo=utc))),
                ('delivery_charge', models.DecimalField(decimal_places=6, default=40.0, max_digits=10)),
                ('waiting_status', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant1.Item')),
                ('delivery_boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_boy.deliveryboy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderingOnline.customer')),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('discount', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='rdata',
            field=models.ManyToManyField(related_name='rest_items', to='Restaurant1.restaurant'),
        ),
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('final_amount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('Items_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.Item')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Items_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='userdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_no', models.CharField(default=None, max_length=12)),
                ('bank_password', models.CharField(default=None, max_length=12)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer')),
            ],
        ),
    ]
