# Generated by Django 3.0.4 on 2021-03-29 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_confirm',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 6, 18, 41, 311792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 6, 18, 41, 311792, tzinfo=utc)),
        ),
    ]
